[theme]
base = "dark"
primaryColor = "#38BDF8"
backgroundColor = "#05070D"
secondaryBackgroundColor = "#0F172A"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
